# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pages.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pages_window(object):
    def setupUi(self, pages_window):
        pages_window.setObjectName("pages_window")
        pages_window.resize(700, 600)
        pages_window.setMinimumSize(QtCore.QSize(700, 600))
        pages_window.setMaximumSize(QtCore.QSize(3000, 3000))
        pages_window.setStyleSheet("background-color: #FFFBCE;\n"
"color: #1E6214;\n"
"")
        pages_window.setSizeGripEnabled(False)
        pages_window.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(pages_window)
        self.gridLayout.setObjectName("gridLayout")
        self.text_situation = QtWidgets.QLabel(pages_window)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_situation.setFont(font)
        self.text_situation.setWordWrap(True)
        self.text_situation.setObjectName("text_situation")
        self.gridLayout.addWidget(self.text_situation, 0, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.var1 = QtWidgets.QPushButton(pages_window)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var1.setFont(font)
        self.var1.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.var1.setObjectName("var1")
        self.gridLayout_2.addWidget(self.var1, 0, 0, 1, 1)
        self.var2 = QtWidgets.QPushButton(pages_window)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var2.setFont(font)
        self.var2.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.var2.setObjectName("var2")
        self.gridLayout_2.addWidget(self.var2, 1, 0, 1, 1)
        self.var3 = QtWidgets.QPushButton(pages_window)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var3.setFont(font)
        self.var3.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.var3.setObjectName("var3")
        self.gridLayout_2.addWidget(self.var3, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.img_label = QtWidgets.QLabel(pages_window)
        self.img_label.setMinimumSize(QtCore.QSize(251, 251))
        self.img_label.setMaximumSize(QtCore.QSize(251, 251))
        self.img_label.setText("")
        self.img_label.setWordWrap(True)
        self.img_label.setObjectName("img_label")
        self.gridLayout.addWidget(self.img_label, 1, 1, 1, 1)
        self.ToTeachersClass = QtWidgets.QPushButton(pages_window)
        self.ToTeachersClass.setMaximumSize(QtCore.QSize(290, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ToTeachersClass.setFont(font)
        self.ToTeachersClass.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.ToTeachersClass.setObjectName("ToTeachersClass")
        self.gridLayout.addWidget(self.ToTeachersClass, 2, 0, 1, 1)
        self.DopInfo = QtWidgets.QPushButton(pages_window)
        self.DopInfo.setMaximumSize(QtCore.QSize(290, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DopInfo.setFont(font)
        self.DopInfo.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.DopInfo.setObjectName("DopInfo")
        self.gridLayout.addWidget(self.DopInfo, 2, 1, 1, 1)

        self.retranslateUi(pages_window)
        QtCore.QMetaObject.connectSlotsByName(pages_window)

    def retranslateUi(self, pages_window):
        _translate = QtCore.QCoreApplication.translate
        pages_window.setWindowTitle(_translate("pages_window", "Решаем ситуацию"))
        self.text_situation.setText(_translate("pages_window", "Текст, описание ситуации, описание этапа, на котором необходимо сделать выбор"))
        self.var1.setText(_translate("pages_window", "Вариант 1"))
        self.var2.setText(_translate("pages_window", "Вариант 2"))
        self.var3.setText(_translate("pages_window", "Вариант 3"))
        self.ToTeachersClass.setText(_translate("pages_window", "Вернуться в учительскую"))
        self.DopInfo.setText(_translate("pages_window", "Доп.информация"))
