# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pages_max.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pages_window(object):
    def setupUi(self, pages_window):
        pages_window.setObjectName("pages_window")
        pages_window.resize(1147, 896)
        pages_window.setMinimumSize(QtCore.QSize(700, 600))
        pages_window.setMaximumSize(QtCore.QSize(3000, 3000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Приложение/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pages_window.setWindowIcon(icon)
        pages_window.setStyleSheet("background-color: #FFFBCE;\n"
"color: #1E6214;\n"
"")
        pages_window.setSizeGripEnabled(False)
        pages_window.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(pages_window)
        self.gridLayout.setObjectName("gridLayout")
        self.Choises = QtWidgets.QVBoxLayout()
        self.Choises.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Choises.setContentsMargins(0, 0, -1, -1)
        self.Choises.setSpacing(0)
        self.Choises.setObjectName("Choises")
        self.var1 = QtWidgets.QPushButton(pages_window)
        self.var1.setMinimumSize(QtCore.QSize(0, 80))
        self.var1.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var1.setFont(font)
        self.var1.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.var1.setObjectName("var1")
        self.Choises.addWidget(self.var1)
        self.var2 = QtWidgets.QPushButton(pages_window)
        self.var2.setMinimumSize(QtCore.QSize(0, 80))
        self.var2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var2.setFont(font)
        self.var2.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.var2.setObjectName("var2")
        self.Choises.addWidget(self.var2)
        self.var3 = QtWidgets.QPushButton(pages_window)
        self.var3.setMinimumSize(QtCore.QSize(0, 80))
        self.var3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var3.setFont(font)
        self.var3.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.var3.setObjectName("var3")
        self.Choises.addWidget(self.var3)
        self.var4 = QtWidgets.QPushButton(pages_window)
        self.var4.setMinimumSize(QtCore.QSize(0, 80))
        self.var4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var4.setFont(font)
        self.var4.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.var4.setObjectName("var4")
        self.Choises.addWidget(self.var4)
        self.var5 = QtWidgets.QPushButton(pages_window)
        self.var5.setMinimumSize(QtCore.QSize(0, 80))
        self.var5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var5.setFont(font)
        self.var5.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.var5.setObjectName("var5")
        self.Choises.addWidget(self.var5)
        self.var6 = QtWidgets.QPushButton(pages_window)
        self.var6.setMinimumSize(QtCore.QSize(0, 80))
        self.var6.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.var6.setFont(font)
        self.var6.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.var6.setObjectName("var6")
        self.Choises.addWidget(self.var6)
        self.gridLayout.addLayout(self.Choises, 4, 0, 2, 3)
        self.ToTeachersClass = QtWidgets.QPushButton(pages_window)
        self.ToTeachersClass.setMinimumSize(QtCore.QSize(0, 80))
        self.ToTeachersClass.setMaximumSize(QtCore.QSize(290, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ToTeachersClass.setFont(font)
        self.ToTeachersClass.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.ToTeachersClass.setObjectName("ToTeachersClass")
        self.gridLayout.addWidget(self.ToTeachersClass, 0, 0, 1, 1)
        self.img_label = QtWidgets.QLabel(pages_window)
        self.img_label.setMinimumSize(QtCore.QSize(300, 300))
        self.img_label.setMaximumSize(QtCore.QSize(600, 600))
        self.img_label.setStyleSheet("border-style:solid;\n"
"border-width:3px;\n"
"border-color:black;\n"
"margin:10px")
        self.img_label.setText("")
        self.img_label.setWordWrap(True)
        self.img_label.setObjectName("img_label")
        self.gridLayout.addWidget(self.img_label, 1, 0, 1, 1)
        self.text_situation = QtWidgets.QLabel(pages_window)
        self.text_situation.setMinimumSize(QtCore.QSize(200, 200))
        self.text_situation.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_situation.setFont(font)
        self.text_situation.setStyleSheet("margin:10px")
        self.text_situation.setWordWrap(True)
        self.text_situation.setObjectName("text_situation")
        self.gridLayout.addWidget(self.text_situation, 0, 1, 3, 2)

        self.retranslateUi(pages_window)
        QtCore.QMetaObject.connectSlotsByName(pages_window)

    def retranslateUi(self, pages_window):
        _translate = QtCore.QCoreApplication.translate
        pages_window.setWindowTitle(_translate("pages_window", "Решаем ситуацию"))
        self.var1.setText(_translate("pages_window", "Вариант 1"))
        self.var2.setText(_translate("pages_window", "Вариант 2"))
        self.var3.setText(_translate("pages_window", "Вариант 3"))
        self.var4.setText(_translate("pages_window", "Вариант 4"))
        self.var5.setText(_translate("pages_window", "Вариант 5"))
        self.var6.setText(_translate("pages_window", "Вариант 6"))
        self.ToTeachersClass.setText(_translate("pages_window", "Вернуться\n"
"в учительскую"))
        self.text_situation.setText(_translate("pages_window", "Текст, описание ситуации, описание этапа, на котором необходимо сделать выбор"))
