# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'problems.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_problems_window(object):
    def setupUi(self, problems_window):
        problems_window.setObjectName("problems_window")
        problems_window.resize(700, 600)
        problems_window.setMinimumSize(QtCore.QSize(700, 600))
        problems_window.setMaximumSize(QtCore.QSize(3000, 3000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Приложение/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        problems_window.setWindowIcon(icon)
        problems_window.setStyleSheet("background-color: #FFFBCE;\n"
"color: #1E6214;\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(problems_window)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(problems_window)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("margin:10px;\n"
"padding:10px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.list_Problems = QtWidgets.QListWidget(problems_window)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.list_Problems.setFont(font)
        self.list_Problems.setStyleSheet("color:#1E6214;background-color:rgb(129, 255, 101);margin:10px;padding:10px")
        self.list_Problems.setObjectName("list_Problems")
        item = QtWidgets.QListWidgetItem()
        self.list_Problems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_Problems.addItem(item)
        self.gridLayout.addWidget(self.list_Problems, 1, 0, 1, 1)
        self.back = QtWidgets.QPushButton(problems_window)
        self.back.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px\n"
"}")
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 2, 0, 1, 1)

        self.retranslateUi(problems_window)
        QtCore.QMetaObject.connectSlotsByName(problems_window)

    def retranslateUi(self, problems_window):
        _translate = QtCore.QCoreApplication.translate
        problems_window.setWindowTitle(_translate("problems_window", "Выбор ситуации"))
        self.label.setText(_translate("problems_window", "Выберите проблему"))
        __sortingEnabled = self.list_Problems.isSortingEnabled()
        self.list_Problems.setSortingEnabled(False)
        item = self.list_Problems.item(0)
        item.setText(_translate("problems_window", "Ребенок прогулял занятие"))
        item = self.list_Problems.item(1)
        item.setText(_translate("problems_window", "Ребенок стесняется отвечать на вопросы"))
        self.list_Problems.setSortingEnabled(__sortingEnabled)
        self.back.setText(_translate("problems_window", "Вернуться в учительскую"))
