# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_window(object):
    def setupUi(self, register_window):
        register_window.setObjectName("register_window")
        register_window.resize(450, 420)
        register_window.setMinimumSize(QtCore.QSize(450, 420))
        register_window.setMaximumSize(QtCore.QSize(450, 420))
        register_window.setStyleSheet("background-color: #FFFBCE;\n"
"color: #1E6214;\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(register_window)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(register_window)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(register_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.login = QtWidgets.QLineEdit(register_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color:#60C04C;\n"
"color:rgb(3, 58, 3);")
        self.login.setObjectName("login")
        self.horizontalLayout_2.addWidget(self.login)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(register_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(register_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:#60C04C;\n"
"color:rgb(3, 58, 3);")
        self.password.setObjectName("password")
        self.horizontalLayout_3.addWidget(self.password)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Vhod = QtWidgets.QPushButton(register_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Vhod.setFont(font)
        self.Vhod.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.Vhod.setObjectName("Vhod")
        self.horizontalLayout.addWidget(self.Vhod)
        self.registerUser = QtWidgets.QPushButton(register_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.registerUser.setFont(font)
        self.registerUser.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"}")
        self.registerUser.setObjectName("registerUser")
        self.horizontalLayout.addWidget(self.registerUser)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(register_window)
        QtCore.QMetaObject.connectSlotsByName(register_window)

    def retranslateUi(self, register_window):
        _translate = QtCore.QCoreApplication.translate
        register_window.setWindowTitle(_translate("register_window", "Вход в систему"))
        self.label.setText(_translate("register_window", "Вход в систему"))
        self.label_2.setText(_translate("register_window", "Логин"))
        self.label_3.setText(_translate("register_window", "Пароль"))
        self.Vhod.setText(_translate("register_window", "Вход"))
        self.registerUser.setText(_translate("register_window", "Зарегестрироваться"))
