# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uchitelhouse_copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uchitelhouse_window(object):
    def setupUi(self, uchitelhouse_window):
        uchitelhouse_window.setObjectName("uchitelhouse_window")
        uchitelhouse_window.resize(700, 600)
        uchitelhouse_window.setMinimumSize(QtCore.QSize(700, 600))
        uchitelhouse_window.setMaximumSize(QtCore.QSize(700, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Приложение/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        uchitelhouse_window.setWindowIcon(icon)
        uchitelhouse_window.setStyleSheet("background-color: #FFFBCE;\n"
"color: #1E6214;\n"
"")
        uchitelhouse_window.setSizeGripEnabled(False)
        uchitelhouse_window.setModal(False)
        self.label = QtWidgets.QLabel(uchitelhouse_window)
        self.label.setGeometry(QtCore.QRect(20, 20, 661, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.img_label = QtWidgets.QLabel(uchitelhouse_window)
        self.img_label.setGeometry(QtCore.QRect(10, 140, 251, 251))
        self.img_label.setMinimumSize(QtCore.QSize(251, 251))
        self.img_label.setMaximumSize(QtCore.QSize(251, 251))
        self.img_label.setStyleSheet("border-style:solid;\n"
"border-width:3px;\n"
"border-color:black;\n"
"margin:10px")
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap("../../../Screenshot_20250404_094444.png"))
        self.img_label.setScaledContents(True)
        self.img_label.setWordWrap(True)
        self.img_label.setObjectName("img_label")
        self.tomainmenu = QtWidgets.QPushButton(uchitelhouse_window)
        self.tomainmenu.setGeometry(QtCore.QRect(270, 150, 391, 121))
        self.tomainmenu.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tomainmenu.setFont(font)
        self.tomainmenu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tomainmenu.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px;\n"
"}")
        self.tomainmenu.setObjectName("tomainmenu")
        self.tomainmenu_2 = QtWidgets.QPushButton(uchitelhouse_window)
        self.tomainmenu_2.setGeometry(QtCore.QRect(270, 270, 391, 121))
        self.tomainmenu_2.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tomainmenu_2.setFont(font)
        self.tomainmenu_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tomainmenu_2.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px;\n"
"}")
        self.tomainmenu_2.setObjectName("tomainmenu_2")
        self.tomainmenu_3 = QtWidgets.QPushButton(uchitelhouse_window)
        self.tomainmenu_3.setGeometry(QtCore.QRect(270, 460, 391, 121))
        self.tomainmenu_3.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tomainmenu_3.setFont(font)
        self.tomainmenu_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tomainmenu_3.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px;\n"
"}")
        self.tomainmenu_3.setObjectName("tomainmenu_3")

        self.retranslateUi(uchitelhouse_window)
        QtCore.QMetaObject.connectSlotsByName(uchitelhouse_window)

    def retranslateUi(self, uchitelhouse_window):
        _translate = QtCore.QCoreApplication.translate
        uchitelhouse_window.setWindowTitle(_translate("uchitelhouse_window", "Учительская"))
        self.label.setText(_translate("uchitelhouse_window", "Учительская"))
        self.tomainmenu.setText(_translate("uchitelhouse_window", "Начать игру"))
        self.tomainmenu_2.setText(_translate("uchitelhouse_window", "Правила"))
        self.tomainmenu_3.setText(_translate("uchitelhouse_window", "Выход"))
