# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uchitelhouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uchitelhouse_window(object):
    def setupUi(self, uchitelhouse_window):
        uchitelhouse_window.setObjectName("uchitelhouse_window")
        uchitelhouse_window.resize(700, 600)
        uchitelhouse_window.setMinimumSize(QtCore.QSize(700, 600))
        uchitelhouse_window.setMaximumSize(QtCore.QSize(700, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Приложение/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        uchitelhouse_window.setWindowIcon(icon)
        uchitelhouse_window.setStyleSheet("background-color: #FFFBCE;\n"
"color: #1E6214;\n"
"")
        uchitelhouse_window.setSizeGripEnabled(False)
        uchitelhouse_window.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(uchitelhouse_window)
        self.gridLayout.setObjectName("gridLayout")
        self.tosituations = QtWidgets.QPushButton(uchitelhouse_window)
        self.tosituations.setMinimumSize(QtCore.QSize(0, 100))
        self.tosituations.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(20)  # Устанавливаем размер шрифта (например, 30)
        self.tosituations.setFont(font)
        self.tosituations.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tosituations.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px;\n"
"}")
        self.tosituations.setObjectName("tosituations")
        self.gridLayout.addWidget(self.tosituations, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(uchitelhouse_window)
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label.setMaximumHeight(100)
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.img_label = QtWidgets.QLabel(uchitelhouse_window)
        self.img_label.setMinimumSize(QtCore.QSize(251, 251))
        self.img_label.setMaximumSize(QtCore.QSize(251, 251))
        self.img_label.setStyleSheet("border-style:solid;\n"
"border-width:3px;\n"
"border-color:black;\n"
"margin:10px")
        self.img_label.setText("")
        self.img_label.setWordWrap(True)
        self.img_label.setObjectName("img_label")
        self.gridLayout.addWidget(self.img_label, 1, 2, 1, 1)
        self.tomainmenu = QtWidgets.QPushButton(uchitelhouse_window)
        self.tomainmenu.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(20)  # Устанавливаем размер шрифта (например, 30)
        self.tomainmenu.setFont(font)
        self.tomainmenu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tomainmenu.setStyleSheet("QPushButton{\n"
"background-color:#1E6214;\n"
"color:#FFFBCE;\n"
"margin:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60C04C;\n"
"color:#1E6214;\n"
"border: 4px solid #60C04C;\n"
"margin:15px;\n"
"}")
        self.tomainmenu.setObjectName("tomainmenu")
        self.gridLayout.addWidget(self.tomainmenu, 2, 0, 1, 1)
        self.personalinfo = QtWidgets.QLabel(uchitelhouse_window)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(15)  # Устанавливаем размер шрифта (например, 30)
        self.personalinfo.setFont(font)
        self.personalinfo.setStyleSheet("padding:10px")
        self.personalinfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.personalinfo.setWordWrap(True)
        self.personalinfo.setObjectName("personalinfo")
        self.gridLayout.addWidget(self.personalinfo, 1, 0, 1, 1)

        self.retranslateUi(uchitelhouse_window)
        QtCore.QMetaObject.connectSlotsByName(uchitelhouse_window)

    def retranslateUi(self, uchitelhouse_window):
        _translate = QtCore.QCoreApplication.translate
        uchitelhouse_window.setWindowTitle(_translate("uchitelhouse_window", "Учительская"))
        self.tosituations.setText(_translate("uchitelhouse_window", "К решению"))
        self.label.setText(_translate("uchitelhouse_window", "Учительская"))
        self.tomainmenu.setText(_translate("uchitelhouse_window", "В главное меню"))
        self.personalinfo.setText(_translate("uchitelhouse_window", "В будущем на этой странице можно будет увидеть информацию о пользователе и сохранять результаты игры"))
